---
# defaults file for ansible-gentoo
disk:
  main: /dev/sda
  main_size: 100%
  swap_size: 4GiB
  filesystem: ext4
  encrypt_with_luks: true
  luks_password: changeme
mirror: http://mirror.mdfnet.se/gentoo
portage:
  cflags: -march=native -O2 -pipe
  cxxflags: ${CFLAGS}
  chost: x86_64-pc-linux-gnu
  use: bindist dbus alsa -X -gnome -dvd -cdr -ipv6 -systemd -gtk -gtk3
  cpu_flags_x86: mmx sse sse2 mmxext
  makeopts: -j{{ ansible_processor_count + 1 }}
  features: sandbox parallel-fetch candy userfetch webrsync-gpg
  portage_gpg_dir: /var/lib/gentoo/gkeys/keyrings/gentoo/release
gentoo_gpg_keys:
  - 0xBB572E0E2D182910
  - 0xDB6B8C1F96D8BF6D
  - 0x9E6438C817072058
timezone: Europe/Brussels
hostname: create-a-super-nice-name

domain: met.tfoundry.com
kernel: config-3.13.0-24-generic
management_interface: "{{ ansible_default_ipv4.interface }}"
pubkey: ~/.ssh/id_ed25519.pub
root_passwd: gentoo-root
gateway: "{{ ansible_default_ipv4.gateway }}"
netmask: "{{ ansible_default_ipv4.netmask }}"
